query blogQuery {
  blogs {
    data {
      attributes {
        title
        views
        content
        date
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
